### ISSUE TITLE
Support tab completion?

### ISSUE THREAD

**Issue by kentcdodds** [nicksrandall/inquierer-directory#1]
Hi @nicksrandall, does this plugin support tab completion for the directory? I'll definitely use it if it does.

**Comment by nicksrandall** [comment]
Hey @kentcdodds! Not yet but comming soon. :smile:

**Comment by nicksrandall** [comment]
@kentcdodds I've added the functionality to type a letter and have your cursor jump to the first folder that starts with that letter (the folder list is also sorted). I want to add the ability to type mutliplle letters consecuitvely (example: "redu" => "reducers") but I haven't got that far yet. 

Also, these changes introduced a breaking change that disables "vim" style navigation of the list (ie. "k" + "j" to go up and down)

**Comment by nicksrandall** [comment]
True "tab completion" is another beast entirley.
