### ISSUE TITLE
Make 'choose this directory' default

### ISSUE THREAD

**Issue by vincentvanderweele** [nicksrandall/inquierer-directory#10]
I'm using inquirer-directory with plop to generate components. Sometimes I want to generate nested components, but 90% of the time I want to generate in the components root folder.

With the current default of inquirer-directory I cannot just enter my way through the menu, because I need to navigate to 'choose this directory'. Not a big deal but it still requires some extra brain cycles :)

It would be nice if one of the following could be done:
1. Display 'choose this directory' as the first list item, rather than the last
2. Start with the cursor at 'choose this directory'
3. Make the position of 'choose this directory' configurable (top, bottom, some other way?)
4. Any other way to make the base directory the default

How do you feel, would that make sense?

**Comment by fesor** [comment]
Maybe if there is default value specified, then we should start travers directories not from `basePath` but from `default` value, and then we could just set cursor to `choose this directory` by default?

**Comment by nicksrandall** [comment]
I don't really maintain this REPO anymore and this issue is old so I'm going to close it.
