### ISSUE TITLE
promises

### ISSUE THREAD

**Issue by ORESoftware** [nicksrandall/inquierer-directory#12]
Does this library work with promises?

If so, maybe put that in the readme? I am hoping it does, because inquirer works with promises.

thanks

**Comment by amwmedia** [comment]
currently this library is still based on inquirer 0.X which did not support promises. There is currently a PR out there to update it. Hopefully it'll get pulled in soon.

**Comment by nicksrandall** [comment]
fixed via https://github.com/nicksrandall/inquirer-directory/releases/tag/v2.1.0
