### ISSUE TITLE
Choose multiple directories in one session

### ISSUE THREAD

**Issue by ORESoftware** [nicksrandall/inquierer-directory#15]
we have the promise callback:

```js
.then(function(answers){

});
```

this seems to suggest that we could select multiple directories during one round of selection.
However, my brief experience with this lib seems to dictate that you can only select one directory with each go-around.

Please help me out - can we select multiple directories without invoking `inquirer.prompt()` twice?

If not, please change the semantics to singular "answer" instead of "answers"

```js
.then(function(answer){

});
```

**Comment by ORESoftware** [comment]
submitted a PR for this

**Comment by amwmedia** [comment]
For clarification, answers would include answers to all prompts presented to the user.

**Comment by ORESoftware** [comment]
Yeah ok that makes sense, but what about handling callbacks as well as
promises?

**Comment by amwmedia** [comment]
I thought the 1.x version of inquirer was all promises now. So you would need to call inquirer with an array of prompts you want to present to the user, and the `.then(answers => {})` function afterward can do stuff based all the user's responses.

**Comment by amwmedia** [comment]
not sure I know where the callbacks fit into it

**Comment by nicksrandall** [comment]
I don't really maintain this REPO anymore and this issue is old so I'm going to close it.
