### ISSUE TITLE
option to select file path

### ISSUE THREAD

**Issue by ORESoftware** [nicksrandall/inquierer-directory#17]
Is there an option we can pass to this library such that we can select file paths as well as directory paths?

Would be very useful for my use case, thanks!

**Comment by ORESoftware** [comment]
Would you accept a PR for this?

I assume there should be some boolean flag passed into the system like so:

``` js
inquirer.prompt([
 { 
  name: 'chosenFile',
  type: 'directory',
  baseDir: '.',
  includeFiles: true,         // <<<<<<<
 }
]).then(function(answers){

});
```

let me know if that's the way you would envision it and I can try to make it work.

**Comment by amwmedia** [comment]
I'd want to see what @nicksrandall thinks of the idea/implementation. I can certainly see the benefit to having this type of feature though.

**Comment by nicksrandall** [comment]
I think that a feature like this could be useful. Do you think that users will need to dynamically choose if they want a file or a folder, or would they most likely want just one or the other for a given situation? I don't know about your use cases but the latter feels more true to me. If that is the case, my recommendation would be to fork this repo and to make an inquirer plugin that only selects files (with perhaps the ability to make new files). That way, you have an explicit tool for both files and folders. 

If that is not the case, and you think that dynamic switching would be useful, then I'm open to adding it here. 

Thoughts?

**Comment by amwmedia** [comment]
Agreed. I can't image a use case where the user should be given control to choose either a file or a folder. I would think that the receiving code would have an expectation of what it will get back in `answers`.

I think a fork might be a good choice as it will allow each codebase to create the best experience for its use case.

**Comment by ORESoftware** [comment]
Well I submitted a PR for this, but I said don't merge it.

Basically the way it works is you drill down and eventually get to a single file, and you select it by just hitting enter.

You can try the code I submitted if you want. It should work, but it's not ideal user experience.

**Comment by ORESoftware** [comment]
My use case is I need to allow the user to select either a directory or a file. I need to give them both options.

In the validate function, the developer can force the user to pick a file not a dir, if that's necessary.

**Comment by nicksrandall** [comment]
I don't really maintain this REPO anymore and this issue is old so I'm going to close it.
