### ISSUE TITLE
For large directories, use right / left arrow keys

### ISSUE THREAD

**Issue by ORESoftware** [nicksrandall/inquierer-directory#19]
Imagine a directory with 100 folders, or 1000 folders.... it gets awkward to "choose this directory" -

e.g. if you you want to choose a directory, you would have to navigate (using enter) to the right dir, and then once the current directory is the one you want, then you have to scroll to get to "choose this directory" which means you might have to scroll through 999 items.

Instead, I recommend having an option of right and left arrow keys to navigate through dirs =>

_Left arrow key is to "go up" a directory. Right arrow key is to drill into a directory._

And then enter becomes selecting / choosing the highlighted dir.

Is this an existing setup or is this lib not configured for this?

**Comment by ORESoftware** [comment]
using right and left arrow keys would also solve the very very unlikely scenario where a user has directories named

either:

 'choose this directory'

or:

'go back a directory'

:)

**Comment by amwmedia** [comment]
the case of many directories is solved pretty nicely via the [search mode](https://github.com/nicksrandall/inquirer-directory#key-maps). Though the left/right arrow functionality sound like a nice improvement to me

**Comment by ORESoftware** [comment]
Yeah, I find search mode to be a little less intuitive, I added the right and left arrow key functionality to the PR I submitted yesterday.

If I invited you to that repo could you help me fix it up?

**Comment by amwmedia** [comment]
what repo do you mean?

**Comment by ORESoftware** [comment]
https://github.com/nicksrandall/inquirer-directory/compare/master...ORESoftware-team:alex_suggestions?w=0

take a look at that branch, please see if you like the functionality

**Comment by ORESoftware** [comment]
I just added functionality so that when you navigate up and down folders, it remembers which index you were last time you were there. Quite nice feature, and IMO pretty annoying without it. It just uses a hash to relate a path to the selected index, which is always 1:1.

Also, I don't think you need to store depth (depth++, depth--). It's un-necessary state change.

The only info you need to have is the baseDir, which you already have. If you are at the baseDir (currentDir=baseDir), you can't go back any further.

_With that said_, another improvement in this lib is for the lib to take a boolean val, where the boolean is "allowNavigationAboveBaseDir".

If this boolean is falsy, you prevent the user from moving up directories above the baseDir, if it's true, then you allow the user to move up dirs if they want to.

**Comment by nicksrandall** [comment]
I don't really maintain this REPO anymore and this issue is old so I'm going to close it.
