### ISSUE TITLE
Use https://asciinema.org

### ISSUE THREAD

**Issue by kentcdodds** [nicksrandall/inquierer-directory#2]
You might find this interesting :-) https://asciinema.org

Example from [next-update](https://github.com/bahmutov/next-update) by @bahmutov :-)

**Comment by nicksrandall** [comment]
Thanks @kentcdodds.

**Comment by kentcdodds** [comment]
Oooooh, that demo makes this look slick!

Another thing you might think about using is [LICEcap](http://www.cockos.com/licecap/) so you could include a gif version directly in your README which would be pretty handy. Also, a quick google found [this](https://github.com/icholy/ttygif) which looks cool too :-)

**Comment by amwmedia** [comment]
yeah, i used LICEcap to record the gif in plop's readme. it does a pretty nice job.
