### ISSUE TITLE
Allow default and/or basePath depending on previous answers

### ISSUE THREAD

**Issue by jrencz** [nicksrandall/inquierer-directory#21]
Here's my case: depending on previous answers I'd like to start in different directories.

I found that inquirer-directory [purposefully removes the default](https://github.com/nicksrandall/inquirer-directory/blob/4480babd7f367c22479378d10d8d58a945062c7e/index.js#L49-L50).
Why is that?

The best case scenario for me would be to allow defining paths relative to the base path like this:

```js
{
  type: 'directory',
  name: 'path',
  message: 'Where to put the component?',
  basePath: `./app`,
  default: ({isStateful}) => isStateful ?
    './statefulComponents' :
    './statelessComponents',
},
```

(it should be possible to go back to the base path)

or like this:

```js
{
  type: 'directory',
  name: 'path',
  message: 'Where to put the component?',
  basePath: ({isStateful}) => isStateful ?
    './app/statefulComponents' :
    './app/statelessComponents',
},
```

(in this case navigation to the upper directory would be impossible)

IMO both those options are worth considering.
I'm not sure which one is easier to implement but I guess the latter.

**Comment by nicksrandall** [comment]
I don't really maintain this REPO anymore and this issue is old so I'm going to close it.
