### ISSUE TITLE
Should a filter option be allowed?

### ISSUE THREAD

**Issue by drFabio** [nicksrandall/inquierer-directory#22]
I have a structure on the likes of SOME_PATH/components.
I want to remove the components part in the case the user selected it without knowing so I don't generate SOME_PATH/components/components.

Should be a inquirer-directory option to validate?
I can make a PR if that would be a good idea,

**Comment by nicksrandall** [comment]
I don't really maintain this REPO anymore and this issue is old so I'm going to close it.
