### ISSUE TITLE
basePath should allow an absolute path

### ISSUE THREAD

**Issue by amwmedia** [nicksrandall/inquierer-directory#3]
hey man, I was just trying this out and ran into a little snag. I wanted to make basePath the path of the plopfile (available via plop.getPlopfilePath()) and the plugin errored. I'm guessing that your plugin expects a relative path, but I might be wrong. Didn't have the time to dig in further.

[ENOENT error](https://www.evernote.com/l/AAHE8x_r24ZFOq5prWWYfSiDrQ7rU4Aafy0)
[plopfile code](https://www.evernote.com/l/AAGSr0-_8rtNj40n4FDaffOfkQNsgiyDtEw)

**Comment by nicksrandall** [comment]
@amwmedia I believe I have fixed this. I'll test in plop to make sure.
