### ISSUE TITLE
Vim Style completion

### ISSUE THREAD

**Issue by agarrharr** [nicksrandall/inquierer-directory#5]
I saw in issue #1, that vim style completion was removed in favor of being able to type the first letter of a file to jump to it. Is there any way that we can bring back vim style completion and still make people happy that want auto completion?

Vim style navigation (using j/k to move up/down) is something that I have come to expect in the command line. I'm not sure what the convention is for auto completion though.

@kentcdodds, let me know if you have any thoughts on this.

**Comment by kentcdodds** [comment]
I agree, but I'm not currently using this module so my opinion matters very little ;-)

**Comment by agarrharr** [comment]
My proposal would be to use j/k for up/down and then if the user wants to search, they should first type `/` and then be able to search.

**Comment by nicksrandall** [comment]
@aharris88 As a recent convert to vim, I'm inclined to make this change. That slash command is a good idea. I'll work on it as soon as I can. I'm also open to PRs!

**Comment by agarrharr** [comment]
Cool. To provide more detail. They would type `/`, type their search, hit enter, and then they could type `n` to go the next result, or `N` to go to the previous results. You could, of course provide instructions that `/` will start a search.

**Comment by nicksrandall** [comment]
I think this will be hard to implement but I'm willing to give it a shot.

**Comment by agarrharr** [comment]
Yeah, I was afraid it would be hard. Also, another example of a program that uses this style besides vim is less.

**Comment by amwmedia** [comment]
just a thought, you could potentially use a `vimMode` attribute in the prompt config. Then you could keep the same functionality (no breaking change) and still enable this use case for those who really like this style of navigation.

**Comment by agarrharr** [comment]
@amwmedia I thought about this. But I think the choice should be up to the user of the tool, and not the person who implements this tool (if that makes sense).

**Comment by amwmedia** [comment]
agreed, these types of things are tough because it's hard to find a solution that allows everyone to have it the way they want it.
