### ISSUE TITLE
Feature Request: File selector

### ISSUE THREAD

**Issue by jonathan-fulton** [nicksrandall/inquierer-directory#7]
It would be useful to have the option of selecting files in addition to directories.  How hard would that be to add?  Not sure if it would be easier to integrate here or built a separate repo.  I'm guessing the former but wanted to check.

**Comment by nicksrandall** [comment]
I think this is a good idea. However, I think it should be implemented as a separate component (plugin). If you (or anybody) forked this repo as a starting place, I think it would take a (relatively) minimal amount of effort to add file level selections. I'd be happy to help if you get stuck.
